// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package jwtauthbackendrole

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-vault.jwtAuthBackendRole.JwtAuthBackendRole",
		reflect.TypeOf((*JwtAuthBackendRole)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "aliasMetadata", GoGetter: "AliasMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "aliasMetadataInput", GoGetter: "AliasMetadataInput"},
			_jsii_.MemberProperty{JsiiProperty: "allowedRedirectUris", GoGetter: "AllowedRedirectUris"},
			_jsii_.MemberProperty{JsiiProperty: "allowedRedirectUrisInput", GoGetter: "AllowedRedirectUrisInput"},
			_jsii_.MemberProperty{JsiiProperty: "backend", GoGetter: "Backend"},
			_jsii_.MemberProperty{JsiiProperty: "backendInput", GoGetter: "BackendInput"},
			_jsii_.MemberProperty{JsiiProperty: "boundAudiences", GoGetter: "BoundAudiences"},
			_jsii_.MemberProperty{JsiiProperty: "boundAudiencesInput", GoGetter: "BoundAudiencesInput"},
			_jsii_.MemberProperty{JsiiProperty: "boundClaims", GoGetter: "BoundClaims"},
			_jsii_.MemberProperty{JsiiProperty: "boundClaimsInput", GoGetter: "BoundClaimsInput"},
			_jsii_.MemberProperty{JsiiProperty: "boundClaimsType", GoGetter: "BoundClaimsType"},
			_jsii_.MemberProperty{JsiiProperty: "boundClaimsTypeInput", GoGetter: "BoundClaimsTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "boundSubject", GoGetter: "BoundSubject"},
			_jsii_.MemberProperty{JsiiProperty: "boundSubjectInput", GoGetter: "BoundSubjectInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "claimMappings", GoGetter: "ClaimMappings"},
			_jsii_.MemberProperty{JsiiProperty: "claimMappingsInput", GoGetter: "ClaimMappingsInput"},
			_jsii_.MemberProperty{JsiiProperty: "clockSkewLeeway", GoGetter: "ClockSkewLeeway"},
			_jsii_.MemberProperty{JsiiProperty: "clockSkewLeewayInput", GoGetter: "ClockSkewLeewayInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "disableBoundClaimsParsing", GoGetter: "DisableBoundClaimsParsing"},
			_jsii_.MemberProperty{JsiiProperty: "disableBoundClaimsParsingInput", GoGetter: "DisableBoundClaimsParsingInput"},
			_jsii_.MemberProperty{JsiiProperty: "expirationLeeway", GoGetter: "ExpirationLeeway"},
			_jsii_.MemberProperty{JsiiProperty: "expirationLeewayInput", GoGetter: "ExpirationLeewayInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "groupsClaim", GoGetter: "GroupsClaim"},
			_jsii_.MemberProperty{JsiiProperty: "groupsClaimInput", GoGetter: "GroupsClaimInput"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "maxAge", GoGetter: "MaxAge"},
			_jsii_.MemberProperty{JsiiProperty: "maxAgeInput", GoGetter: "MaxAgeInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "namespace", GoGetter: "Namespace"},
			_jsii_.MemberProperty{JsiiProperty: "namespaceInput", GoGetter: "NamespaceInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "notBeforeLeeway", GoGetter: "NotBeforeLeeway"},
			_jsii_.MemberProperty{JsiiProperty: "notBeforeLeewayInput", GoGetter: "NotBeforeLeewayInput"},
			_jsii_.MemberProperty{JsiiProperty: "oidcScopes", GoGetter: "OidcScopes"},
			_jsii_.MemberProperty{JsiiProperty: "oidcScopesInput", GoGetter: "OidcScopesInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAliasMetadata", GoMethod: "ResetAliasMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowedRedirectUris", GoMethod: "ResetAllowedRedirectUris"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackend", GoMethod: "ResetBackend"},
			_jsii_.MemberMethod{JsiiMethod: "resetBoundAudiences", GoMethod: "ResetBoundAudiences"},
			_jsii_.MemberMethod{JsiiMethod: "resetBoundClaims", GoMethod: "ResetBoundClaims"},
			_jsii_.MemberMethod{JsiiMethod: "resetBoundClaimsType", GoMethod: "ResetBoundClaimsType"},
			_jsii_.MemberMethod{JsiiMethod: "resetBoundSubject", GoMethod: "ResetBoundSubject"},
			_jsii_.MemberMethod{JsiiMethod: "resetClaimMappings", GoMethod: "ResetClaimMappings"},
			_jsii_.MemberMethod{JsiiMethod: "resetClockSkewLeeway", GoMethod: "ResetClockSkewLeeway"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableBoundClaimsParsing", GoMethod: "ResetDisableBoundClaimsParsing"},
			_jsii_.MemberMethod{JsiiMethod: "resetExpirationLeeway", GoMethod: "ResetExpirationLeeway"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupsClaim", GoMethod: "ResetGroupsClaim"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxAge", GoMethod: "ResetMaxAge"},
			_jsii_.MemberMethod{JsiiMethod: "resetNamespace", GoMethod: "ResetNamespace"},
			_jsii_.MemberMethod{JsiiMethod: "resetNotBeforeLeeway", GoMethod: "ResetNotBeforeLeeway"},
			_jsii_.MemberMethod{JsiiMethod: "resetOidcScopes", GoMethod: "ResetOidcScopes"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetRoleType", GoMethod: "ResetRoleType"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenBoundCidrs", GoMethod: "ResetTokenBoundCidrs"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenExplicitMaxTtl", GoMethod: "ResetTokenExplicitMaxTtl"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenMaxTtl", GoMethod: "ResetTokenMaxTtl"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenNoDefaultPolicy", GoMethod: "ResetTokenNoDefaultPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenNumUses", GoMethod: "ResetTokenNumUses"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenPeriod", GoMethod: "ResetTokenPeriod"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenPolicies", GoMethod: "ResetTokenPolicies"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenTtl", GoMethod: "ResetTokenTtl"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenType", GoMethod: "ResetTokenType"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserClaimJsonPointer", GoMethod: "ResetUserClaimJsonPointer"},
			_jsii_.MemberMethod{JsiiMethod: "resetVerboseOidcLogging", GoMethod: "ResetVerboseOidcLogging"},
			_jsii_.MemberProperty{JsiiProperty: "roleName", GoGetter: "RoleName"},
			_jsii_.MemberProperty{JsiiProperty: "roleNameInput", GoGetter: "RoleNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "roleType", GoGetter: "RoleType"},
			_jsii_.MemberProperty{JsiiProperty: "roleTypeInput", GoGetter: "RoleTypeInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "tokenBoundCidrs", GoGetter: "TokenBoundCidrs"},
			_jsii_.MemberProperty{JsiiProperty: "tokenBoundCidrsInput", GoGetter: "TokenBoundCidrsInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenExplicitMaxTtl", GoGetter: "TokenExplicitMaxTtl"},
			_jsii_.MemberProperty{JsiiProperty: "tokenExplicitMaxTtlInput", GoGetter: "TokenExplicitMaxTtlInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenMaxTtl", GoGetter: "TokenMaxTtl"},
			_jsii_.MemberProperty{JsiiProperty: "tokenMaxTtlInput", GoGetter: "TokenMaxTtlInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenNoDefaultPolicy", GoGetter: "TokenNoDefaultPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "tokenNoDefaultPolicyInput", GoGetter: "TokenNoDefaultPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenNumUses", GoGetter: "TokenNumUses"},
			_jsii_.MemberProperty{JsiiProperty: "tokenNumUsesInput", GoGetter: "TokenNumUsesInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenPeriod", GoGetter: "TokenPeriod"},
			_jsii_.MemberProperty{JsiiProperty: "tokenPeriodInput", GoGetter: "TokenPeriodInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenPolicies", GoGetter: "TokenPolicies"},
			_jsii_.MemberProperty{JsiiProperty: "tokenPoliciesInput", GoGetter: "TokenPoliciesInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenTtl", GoGetter: "TokenTtl"},
			_jsii_.MemberProperty{JsiiProperty: "tokenTtlInput", GoGetter: "TokenTtlInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenType", GoGetter: "TokenType"},
			_jsii_.MemberProperty{JsiiProperty: "tokenTypeInput", GoGetter: "TokenTypeInput"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "userClaim", GoGetter: "UserClaim"},
			_jsii_.MemberProperty{JsiiProperty: "userClaimInput", GoGetter: "UserClaimInput"},
			_jsii_.MemberProperty{JsiiProperty: "userClaimJsonPointer", GoGetter: "UserClaimJsonPointer"},
			_jsii_.MemberProperty{JsiiProperty: "userClaimJsonPointerInput", GoGetter: "UserClaimJsonPointerInput"},
			_jsii_.MemberProperty{JsiiProperty: "verboseOidcLogging", GoGetter: "VerboseOidcLogging"},
			_jsii_.MemberProperty{JsiiProperty: "verboseOidcLoggingInput", GoGetter: "VerboseOidcLoggingInput"},
			_jsii_.MemberMethod{JsiiMethod: "with", GoMethod: "With"},
		},
		func() interface{} {
			j := jsiiProxy_JwtAuthBackendRole{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-vault.jwtAuthBackendRole.JwtAuthBackendRoleConfig",
		reflect.TypeOf((*JwtAuthBackendRoleConfig)(nil)).Elem(),
	)
}
