// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package pkisecretbackendconfigautotidy

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-vault.pkiSecretBackendConfigAutoTidy.PkiSecretBackendConfigAutoTidy",
		reflect.TypeOf((*PkiSecretBackendConfigAutoTidy)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "acmeAccountSafetyBuffer", GoGetter: "AcmeAccountSafetyBuffer"},
			_jsii_.MemberProperty{JsiiProperty: "acmeAccountSafetyBufferInput", GoGetter: "AcmeAccountSafetyBufferInput"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "backend", GoGetter: "Backend"},
			_jsii_.MemberProperty{JsiiProperty: "backendInput", GoGetter: "BackendInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "enabled", GoGetter: "Enabled"},
			_jsii_.MemberProperty{JsiiProperty: "enabledInput", GoGetter: "EnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "intervalDuration", GoGetter: "IntervalDuration"},
			_jsii_.MemberProperty{JsiiProperty: "intervalDurationInput", GoGetter: "IntervalDurationInput"},
			_jsii_.MemberProperty{JsiiProperty: "issuerSafetyBuffer", GoGetter: "IssuerSafetyBuffer"},
			_jsii_.MemberProperty{JsiiProperty: "issuerSafetyBufferInput", GoGetter: "IssuerSafetyBufferInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "maintainStoredCertificateCounts", GoGetter: "MaintainStoredCertificateCounts"},
			_jsii_.MemberProperty{JsiiProperty: "maintainStoredCertificateCountsInput", GoGetter: "MaintainStoredCertificateCountsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxStartupBackoffDuration", GoGetter: "MaxStartupBackoffDuration"},
			_jsii_.MemberProperty{JsiiProperty: "maxStartupBackoffDurationInput", GoGetter: "MaxStartupBackoffDurationInput"},
			_jsii_.MemberProperty{JsiiProperty: "minStartupBackoffDuration", GoGetter: "MinStartupBackoffDuration"},
			_jsii_.MemberProperty{JsiiProperty: "minStartupBackoffDurationInput", GoGetter: "MinStartupBackoffDurationInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "namespace", GoGetter: "Namespace"},
			_jsii_.MemberProperty{JsiiProperty: "namespaceInput", GoGetter: "NamespaceInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "pauseDuration", GoGetter: "PauseDuration"},
			_jsii_.MemberProperty{JsiiProperty: "pauseDurationInput", GoGetter: "PauseDurationInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "publishStoredCertificateCountMetrics", GoGetter: "PublishStoredCertificateCountMetrics"},
			_jsii_.MemberProperty{JsiiProperty: "publishStoredCertificateCountMetricsInput", GoGetter: "PublishStoredCertificateCountMetricsInput"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAcmeAccountSafetyBuffer", GoMethod: "ResetAcmeAccountSafetyBuffer"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIntervalDuration", GoMethod: "ResetIntervalDuration"},
			_jsii_.MemberMethod{JsiiMethod: "resetIssuerSafetyBuffer", GoMethod: "ResetIssuerSafetyBuffer"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaintainStoredCertificateCounts", GoMethod: "ResetMaintainStoredCertificateCounts"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxStartupBackoffDuration", GoMethod: "ResetMaxStartupBackoffDuration"},
			_jsii_.MemberMethod{JsiiMethod: "resetMinStartupBackoffDuration", GoMethod: "ResetMinStartupBackoffDuration"},
			_jsii_.MemberMethod{JsiiMethod: "resetNamespace", GoMethod: "ResetNamespace"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPauseDuration", GoMethod: "ResetPauseDuration"},
			_jsii_.MemberMethod{JsiiMethod: "resetPublishStoredCertificateCountMetrics", GoMethod: "ResetPublishStoredCertificateCountMetrics"},
			_jsii_.MemberMethod{JsiiMethod: "resetRevocationQueueSafetyBuffer", GoMethod: "ResetRevocationQueueSafetyBuffer"},
			_jsii_.MemberMethod{JsiiMethod: "resetSafetyBuffer", GoMethod: "ResetSafetyBuffer"},
			_jsii_.MemberMethod{JsiiMethod: "resetTidyAcme", GoMethod: "ResetTidyAcme"},
			_jsii_.MemberMethod{JsiiMethod: "resetTidyCertMetadata", GoMethod: "ResetTidyCertMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "resetTidyCertStore", GoMethod: "ResetTidyCertStore"},
			_jsii_.MemberMethod{JsiiMethod: "resetTidyCmpv2NonceStore", GoMethod: "ResetTidyCmpv2NonceStore"},
			_jsii_.MemberMethod{JsiiMethod: "resetTidyCrossClusterRevokedCerts", GoMethod: "ResetTidyCrossClusterRevokedCerts"},
			_jsii_.MemberMethod{JsiiMethod: "resetTidyExpiredIssuers", GoMethod: "ResetTidyExpiredIssuers"},
			_jsii_.MemberMethod{JsiiMethod: "resetTidyMoveLegacyCaBundle", GoMethod: "ResetTidyMoveLegacyCaBundle"},
			_jsii_.MemberMethod{JsiiMethod: "resetTidyRevocationQueue", GoMethod: "ResetTidyRevocationQueue"},
			_jsii_.MemberMethod{JsiiMethod: "resetTidyRevokedCertIssuerAssociations", GoMethod: "ResetTidyRevokedCertIssuerAssociations"},
			_jsii_.MemberMethod{JsiiMethod: "resetTidyRevokedCerts", GoMethod: "ResetTidyRevokedCerts"},
			_jsii_.MemberProperty{JsiiProperty: "revocationQueueSafetyBuffer", GoGetter: "RevocationQueueSafetyBuffer"},
			_jsii_.MemberProperty{JsiiProperty: "revocationQueueSafetyBufferInput", GoGetter: "RevocationQueueSafetyBufferInput"},
			_jsii_.MemberProperty{JsiiProperty: "safetyBuffer", GoGetter: "SafetyBuffer"},
			_jsii_.MemberProperty{JsiiProperty: "safetyBufferInput", GoGetter: "SafetyBufferInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "tidyAcme", GoGetter: "TidyAcme"},
			_jsii_.MemberProperty{JsiiProperty: "tidyAcmeInput", GoGetter: "TidyAcmeInput"},
			_jsii_.MemberProperty{JsiiProperty: "tidyCertMetadata", GoGetter: "TidyCertMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "tidyCertMetadataInput", GoGetter: "TidyCertMetadataInput"},
			_jsii_.MemberProperty{JsiiProperty: "tidyCertStore", GoGetter: "TidyCertStore"},
			_jsii_.MemberProperty{JsiiProperty: "tidyCertStoreInput", GoGetter: "TidyCertStoreInput"},
			_jsii_.MemberProperty{JsiiProperty: "tidyCmpv2NonceStore", GoGetter: "TidyCmpv2NonceStore"},
			_jsii_.MemberProperty{JsiiProperty: "tidyCmpv2NonceStoreInput", GoGetter: "TidyCmpv2NonceStoreInput"},
			_jsii_.MemberProperty{JsiiProperty: "tidyCrossClusterRevokedCerts", GoGetter: "TidyCrossClusterRevokedCerts"},
			_jsii_.MemberProperty{JsiiProperty: "tidyCrossClusterRevokedCertsInput", GoGetter: "TidyCrossClusterRevokedCertsInput"},
			_jsii_.MemberProperty{JsiiProperty: "tidyExpiredIssuers", GoGetter: "TidyExpiredIssuers"},
			_jsii_.MemberProperty{JsiiProperty: "tidyExpiredIssuersInput", GoGetter: "TidyExpiredIssuersInput"},
			_jsii_.MemberProperty{JsiiProperty: "tidyMoveLegacyCaBundle", GoGetter: "TidyMoveLegacyCaBundle"},
			_jsii_.MemberProperty{JsiiProperty: "tidyMoveLegacyCaBundleInput", GoGetter: "TidyMoveLegacyCaBundleInput"},
			_jsii_.MemberProperty{JsiiProperty: "tidyRevocationQueue", GoGetter: "TidyRevocationQueue"},
			_jsii_.MemberProperty{JsiiProperty: "tidyRevocationQueueInput", GoGetter: "TidyRevocationQueueInput"},
			_jsii_.MemberProperty{JsiiProperty: "tidyRevokedCertIssuerAssociations", GoGetter: "TidyRevokedCertIssuerAssociations"},
			_jsii_.MemberProperty{JsiiProperty: "tidyRevokedCertIssuerAssociationsInput", GoGetter: "TidyRevokedCertIssuerAssociationsInput"},
			_jsii_.MemberProperty{JsiiProperty: "tidyRevokedCerts", GoGetter: "TidyRevokedCerts"},
			_jsii_.MemberProperty{JsiiProperty: "tidyRevokedCertsInput", GoGetter: "TidyRevokedCertsInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
		},
		func() interface{} {
			j := jsiiProxy_PkiSecretBackendConfigAutoTidy{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-vault.pkiSecretBackendConfigAutoTidy.PkiSecretBackendConfigAutoTidyConfig",
		reflect.TypeOf((*PkiSecretBackendConfigAutoTidyConfig)(nil)).Elem(),
	)
}
