// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package kmipsecretrole

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-vault.kmipSecretRole.KmipSecretRole",
		reflect.TypeOf((*KmipSecretRole)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "namespace", GoGetter: "Namespace"},
			_jsii_.MemberProperty{JsiiProperty: "namespaceInput", GoGetter: "NamespaceInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "operationActivate", GoGetter: "OperationActivate"},
			_jsii_.MemberProperty{JsiiProperty: "operationActivateInput", GoGetter: "OperationActivateInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationAddAttribute", GoGetter: "OperationAddAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "operationAddAttributeInput", GoGetter: "OperationAddAttributeInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationAll", GoGetter: "OperationAll"},
			_jsii_.MemberProperty{JsiiProperty: "operationAllInput", GoGetter: "OperationAllInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationCreate", GoGetter: "OperationCreate"},
			_jsii_.MemberProperty{JsiiProperty: "operationCreateInput", GoGetter: "OperationCreateInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationCreateKeyPair", GoGetter: "OperationCreateKeyPair"},
			_jsii_.MemberProperty{JsiiProperty: "operationCreateKeyPairInput", GoGetter: "OperationCreateKeyPairInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationDecrypt", GoGetter: "OperationDecrypt"},
			_jsii_.MemberProperty{JsiiProperty: "operationDecryptInput", GoGetter: "OperationDecryptInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationDeleteAttribute", GoGetter: "OperationDeleteAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "operationDeleteAttributeInput", GoGetter: "OperationDeleteAttributeInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationDestroy", GoGetter: "OperationDestroy"},
			_jsii_.MemberProperty{JsiiProperty: "operationDestroyInput", GoGetter: "OperationDestroyInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationDiscoverVersions", GoGetter: "OperationDiscoverVersions"},
			_jsii_.MemberProperty{JsiiProperty: "operationDiscoverVersionsInput", GoGetter: "OperationDiscoverVersionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationEncrypt", GoGetter: "OperationEncrypt"},
			_jsii_.MemberProperty{JsiiProperty: "operationEncryptInput", GoGetter: "OperationEncryptInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationGet", GoGetter: "OperationGet"},
			_jsii_.MemberProperty{JsiiProperty: "operationGetAttributeList", GoGetter: "OperationGetAttributeList"},
			_jsii_.MemberProperty{JsiiProperty: "operationGetAttributeListInput", GoGetter: "OperationGetAttributeListInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationGetAttributes", GoGetter: "OperationGetAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "operationGetAttributesInput", GoGetter: "OperationGetAttributesInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationGetInput", GoGetter: "OperationGetInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationImport", GoGetter: "OperationImport"},
			_jsii_.MemberProperty{JsiiProperty: "operationImportInput", GoGetter: "OperationImportInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationLocate", GoGetter: "OperationLocate"},
			_jsii_.MemberProperty{JsiiProperty: "operationLocateInput", GoGetter: "OperationLocateInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationMac", GoGetter: "OperationMac"},
			_jsii_.MemberProperty{JsiiProperty: "operationMacInput", GoGetter: "OperationMacInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationMacVerify", GoGetter: "OperationMacVerify"},
			_jsii_.MemberProperty{JsiiProperty: "operationMacVerifyInput", GoGetter: "OperationMacVerifyInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationModifyAttribute", GoGetter: "OperationModifyAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "operationModifyAttributeInput", GoGetter: "OperationModifyAttributeInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationNone", GoGetter: "OperationNone"},
			_jsii_.MemberProperty{JsiiProperty: "operationNoneInput", GoGetter: "OperationNoneInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationQuery", GoGetter: "OperationQuery"},
			_jsii_.MemberProperty{JsiiProperty: "operationQueryInput", GoGetter: "OperationQueryInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationRegister", GoGetter: "OperationRegister"},
			_jsii_.MemberProperty{JsiiProperty: "operationRegisterInput", GoGetter: "OperationRegisterInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationRekey", GoGetter: "OperationRekey"},
			_jsii_.MemberProperty{JsiiProperty: "operationRekeyInput", GoGetter: "OperationRekeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationRekeyKeyPair", GoGetter: "OperationRekeyKeyPair"},
			_jsii_.MemberProperty{JsiiProperty: "operationRekeyKeyPairInput", GoGetter: "OperationRekeyKeyPairInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationRevoke", GoGetter: "OperationRevoke"},
			_jsii_.MemberProperty{JsiiProperty: "operationRevokeInput", GoGetter: "OperationRevokeInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationRngRetrieve", GoGetter: "OperationRngRetrieve"},
			_jsii_.MemberProperty{JsiiProperty: "operationRngRetrieveInput", GoGetter: "OperationRngRetrieveInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationRngSeed", GoGetter: "OperationRngSeed"},
			_jsii_.MemberProperty{JsiiProperty: "operationRngSeedInput", GoGetter: "OperationRngSeedInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationSign", GoGetter: "OperationSign"},
			_jsii_.MemberProperty{JsiiProperty: "operationSignatureVerify", GoGetter: "OperationSignatureVerify"},
			_jsii_.MemberProperty{JsiiProperty: "operationSignatureVerifyInput", GoGetter: "OperationSignatureVerifyInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationSignInput", GoGetter: "OperationSignInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "path", GoGetter: "Path"},
			_jsii_.MemberProperty{JsiiProperty: "pathInput", GoGetter: "PathInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetNamespace", GoMethod: "ResetNamespace"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationActivate", GoMethod: "ResetOperationActivate"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationAddAttribute", GoMethod: "ResetOperationAddAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationAll", GoMethod: "ResetOperationAll"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationCreate", GoMethod: "ResetOperationCreate"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationCreateKeyPair", GoMethod: "ResetOperationCreateKeyPair"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationDecrypt", GoMethod: "ResetOperationDecrypt"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationDeleteAttribute", GoMethod: "ResetOperationDeleteAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationDestroy", GoMethod: "ResetOperationDestroy"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationDiscoverVersions", GoMethod: "ResetOperationDiscoverVersions"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationEncrypt", GoMethod: "ResetOperationEncrypt"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationGet", GoMethod: "ResetOperationGet"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationGetAttributeList", GoMethod: "ResetOperationGetAttributeList"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationGetAttributes", GoMethod: "ResetOperationGetAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationImport", GoMethod: "ResetOperationImport"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationLocate", GoMethod: "ResetOperationLocate"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationMac", GoMethod: "ResetOperationMac"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationMacVerify", GoMethod: "ResetOperationMacVerify"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationModifyAttribute", GoMethod: "ResetOperationModifyAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationNone", GoMethod: "ResetOperationNone"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationQuery", GoMethod: "ResetOperationQuery"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationRegister", GoMethod: "ResetOperationRegister"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationRekey", GoMethod: "ResetOperationRekey"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationRekeyKeyPair", GoMethod: "ResetOperationRekeyKeyPair"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationRevoke", GoMethod: "ResetOperationRevoke"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationRngRetrieve", GoMethod: "ResetOperationRngRetrieve"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationRngSeed", GoMethod: "ResetOperationRngSeed"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationSign", GoMethod: "ResetOperationSign"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationSignatureVerify", GoMethod: "ResetOperationSignatureVerify"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetTlsClientKeyBits", GoMethod: "ResetTlsClientKeyBits"},
			_jsii_.MemberMethod{JsiiMethod: "resetTlsClientKeyType", GoMethod: "ResetTlsClientKeyType"},
			_jsii_.MemberMethod{JsiiMethod: "resetTlsClientTtl", GoMethod: "ResetTlsClientTtl"},
			_jsii_.MemberProperty{JsiiProperty: "role", GoGetter: "Role"},
			_jsii_.MemberProperty{JsiiProperty: "roleInput", GoGetter: "RoleInput"},
			_jsii_.MemberProperty{JsiiProperty: "scope", GoGetter: "Scope"},
			_jsii_.MemberProperty{JsiiProperty: "scopeInput", GoGetter: "ScopeInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "tlsClientKeyBits", GoGetter: "TlsClientKeyBits"},
			_jsii_.MemberProperty{JsiiProperty: "tlsClientKeyBitsInput", GoGetter: "TlsClientKeyBitsInput"},
			_jsii_.MemberProperty{JsiiProperty: "tlsClientKeyType", GoGetter: "TlsClientKeyType"},
			_jsii_.MemberProperty{JsiiProperty: "tlsClientKeyTypeInput", GoGetter: "TlsClientKeyTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "tlsClientTtl", GoGetter: "TlsClientTtl"},
			_jsii_.MemberProperty{JsiiProperty: "tlsClientTtlInput", GoGetter: "TlsClientTtlInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
		},
		func() interface{} {
			j := jsiiProxy_KmipSecretRole{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-vault.kmipSecretRole.KmipSecretRoleConfig",
		reflect.TypeOf((*KmipSecretRoleConfig)(nil)).Elem(),
	)
}
