// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package awsauthbackendclient

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-vault.awsAuthBackendClient.AwsAuthBackendClient",
		reflect.TypeOf((*AwsAuthBackendClient)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accessKey", GoGetter: "AccessKey"},
			_jsii_.MemberProperty{JsiiProperty: "accessKeyInput", GoGetter: "AccessKeyInput"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "allowedStsHeaderValues", GoGetter: "AllowedStsHeaderValues"},
			_jsii_.MemberProperty{JsiiProperty: "allowedStsHeaderValuesInput", GoGetter: "AllowedStsHeaderValuesInput"},
			_jsii_.MemberProperty{JsiiProperty: "backend", GoGetter: "Backend"},
			_jsii_.MemberProperty{JsiiProperty: "backendInput", GoGetter: "BackendInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "disableAutomatedRotation", GoGetter: "DisableAutomatedRotation"},
			_jsii_.MemberProperty{JsiiProperty: "disableAutomatedRotationInput", GoGetter: "DisableAutomatedRotationInput"},
			_jsii_.MemberProperty{JsiiProperty: "ec2Endpoint", GoGetter: "Ec2Endpoint"},
			_jsii_.MemberProperty{JsiiProperty: "ec2EndpointInput", GoGetter: "Ec2EndpointInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "iamEndpoint", GoGetter: "IamEndpoint"},
			_jsii_.MemberProperty{JsiiProperty: "iamEndpointInput", GoGetter: "IamEndpointInput"},
			_jsii_.MemberProperty{JsiiProperty: "iamServerIdHeaderValue", GoGetter: "IamServerIdHeaderValue"},
			_jsii_.MemberProperty{JsiiProperty: "iamServerIdHeaderValueInput", GoGetter: "IamServerIdHeaderValueInput"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "identityTokenAudience", GoGetter: "IdentityTokenAudience"},
			_jsii_.MemberProperty{JsiiProperty: "identityTokenAudienceInput", GoGetter: "IdentityTokenAudienceInput"},
			_jsii_.MemberProperty{JsiiProperty: "identityTokenTtl", GoGetter: "IdentityTokenTtl"},
			_jsii_.MemberProperty{JsiiProperty: "identityTokenTtlInput", GoGetter: "IdentityTokenTtlInput"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "maxRetries", GoGetter: "MaxRetries"},
			_jsii_.MemberProperty{JsiiProperty: "maxRetriesInput", GoGetter: "MaxRetriesInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "namespace", GoGetter: "Namespace"},
			_jsii_.MemberProperty{JsiiProperty: "namespaceInput", GoGetter: "NamespaceInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessKey", GoMethod: "ResetAccessKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowedStsHeaderValues", GoMethod: "ResetAllowedStsHeaderValues"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackend", GoMethod: "ResetBackend"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableAutomatedRotation", GoMethod: "ResetDisableAutomatedRotation"},
			_jsii_.MemberMethod{JsiiMethod: "resetEc2Endpoint", GoMethod: "ResetEc2Endpoint"},
			_jsii_.MemberMethod{JsiiMethod: "resetIamEndpoint", GoMethod: "ResetIamEndpoint"},
			_jsii_.MemberMethod{JsiiMethod: "resetIamServerIdHeaderValue", GoMethod: "ResetIamServerIdHeaderValue"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIdentityTokenAudience", GoMethod: "ResetIdentityTokenAudience"},
			_jsii_.MemberMethod{JsiiMethod: "resetIdentityTokenTtl", GoMethod: "ResetIdentityTokenTtl"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxRetries", GoMethod: "ResetMaxRetries"},
			_jsii_.MemberMethod{JsiiMethod: "resetNamespace", GoMethod: "ResetNamespace"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetRoleArn", GoMethod: "ResetRoleArn"},
			_jsii_.MemberMethod{JsiiMethod: "resetRotationPeriod", GoMethod: "ResetRotationPeriod"},
			_jsii_.MemberMethod{JsiiMethod: "resetRotationSchedule", GoMethod: "ResetRotationSchedule"},
			_jsii_.MemberMethod{JsiiMethod: "resetRotationWindow", GoMethod: "ResetRotationWindow"},
			_jsii_.MemberMethod{JsiiMethod: "resetSecretKey", GoMethod: "ResetSecretKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetSecretKeyWo", GoMethod: "ResetSecretKeyWo"},
			_jsii_.MemberMethod{JsiiMethod: "resetSecretKeyWoVersion", GoMethod: "ResetSecretKeyWoVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetStsEndpoint", GoMethod: "ResetStsEndpoint"},
			_jsii_.MemberMethod{JsiiMethod: "resetStsRegion", GoMethod: "ResetStsRegion"},
			_jsii_.MemberMethod{JsiiMethod: "resetUseStsRegionFromClient", GoMethod: "ResetUseStsRegionFromClient"},
			_jsii_.MemberProperty{JsiiProperty: "roleArn", GoGetter: "RoleArn"},
			_jsii_.MemberProperty{JsiiProperty: "roleArnInput", GoGetter: "RoleArnInput"},
			_jsii_.MemberProperty{JsiiProperty: "rotationPeriod", GoGetter: "RotationPeriod"},
			_jsii_.MemberProperty{JsiiProperty: "rotationPeriodInput", GoGetter: "RotationPeriodInput"},
			_jsii_.MemberProperty{JsiiProperty: "rotationSchedule", GoGetter: "RotationSchedule"},
			_jsii_.MemberProperty{JsiiProperty: "rotationScheduleInput", GoGetter: "RotationScheduleInput"},
			_jsii_.MemberProperty{JsiiProperty: "rotationWindow", GoGetter: "RotationWindow"},
			_jsii_.MemberProperty{JsiiProperty: "rotationWindowInput", GoGetter: "RotationWindowInput"},
			_jsii_.MemberProperty{JsiiProperty: "secretKey", GoGetter: "SecretKey"},
			_jsii_.MemberProperty{JsiiProperty: "secretKeyInput", GoGetter: "SecretKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "secretKeyWo", GoGetter: "SecretKeyWo"},
			_jsii_.MemberProperty{JsiiProperty: "secretKeyWoInput", GoGetter: "SecretKeyWoInput"},
			_jsii_.MemberProperty{JsiiProperty: "secretKeyWoVersion", GoGetter: "SecretKeyWoVersion"},
			_jsii_.MemberProperty{JsiiProperty: "secretKeyWoVersionInput", GoGetter: "SecretKeyWoVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "stsEndpoint", GoGetter: "StsEndpoint"},
			_jsii_.MemberProperty{JsiiProperty: "stsEndpointInput", GoGetter: "StsEndpointInput"},
			_jsii_.MemberProperty{JsiiProperty: "stsRegion", GoGetter: "StsRegion"},
			_jsii_.MemberProperty{JsiiProperty: "stsRegionInput", GoGetter: "StsRegionInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "useStsRegionFromClient", GoGetter: "UseStsRegionFromClient"},
			_jsii_.MemberProperty{JsiiProperty: "useStsRegionFromClientInput", GoGetter: "UseStsRegionFromClientInput"},
			_jsii_.MemberMethod{JsiiMethod: "with", GoMethod: "With"},
		},
		func() interface{} {
			j := jsiiProxy_AwsAuthBackendClient{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-vault.awsAuthBackendClient.AwsAuthBackendClientConfig",
		reflect.TypeOf((*AwsAuthBackendClientConfig)(nil)).Elem(),
	)
}
