// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package spiffesecretbackendrole

import (
	"github.com/open-constructs/cdk-terrain-go/cdktn"
)

type SpiffeSecretBackendRoleConfig struct {
	// Experimental.
	Connection interface{} `field:"optional" json:"connection" yaml:"connection"`
	// Experimental.
	Count interface{} `field:"optional" json:"count" yaml:"count"`
	// Experimental.
	DependsOn *[]cdktn.ITerraformDependable `field:"optional" json:"dependsOn" yaml:"dependsOn"`
	// Experimental.
	ForEach cdktn.ITerraformIterator `field:"optional" json:"forEach" yaml:"forEach"`
	// Experimental.
	Lifecycle *cdktn.TerraformResourceLifecycle `field:"optional" json:"lifecycle" yaml:"lifecycle"`
	// Experimental.
	Provider cdktn.TerraformProvider `field:"optional" json:"provider" yaml:"provider"`
	// Experimental.
	Provisioners *[]interface{} `field:"optional" json:"provisioners" yaml:"provisioners"`
	// Mount path for the SPIFFE secrets engine in Vault.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/vault/5.10.0/docs/resources/spiffe_secret_backend_role#mount SpiffeSecretBackendRole#mount}
	Mount *string `field:"required" json:"mount" yaml:"mount"`
	// Name of the SPIFFE role.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/vault/5.10.0/docs/resources/spiffe_secret_backend_role#name SpiffeSecretBackendRole#name}
	Name *string `field:"required" json:"name" yaml:"name"`
	// The template string to use for generating tokens. This may be in stringified JSON or base64 format.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/vault/5.10.0/docs/resources/spiffe_secret_backend_role#template SpiffeSecretBackendRole#template}
	Template *string `field:"required" json:"template" yaml:"template"`
	// Target namespace. (requires Enterprise).
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/vault/5.10.0/docs/resources/spiffe_secret_backend_role#namespace SpiffeSecretBackendRole#namespace}
	Namespace *string `field:"optional" json:"namespace" yaml:"namespace"`
	// TTL of the tokens generated by this role.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/vault/5.10.0/docs/resources/spiffe_secret_backend_role#ttl SpiffeSecretBackendRole#ttl}
	Ttl *string `field:"optional" json:"ttl" yaml:"ttl"`
	// If true, the jti (JWT ID) claim will be included in tokens generated from this role.
	//
	// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/vault/5.10.0/docs/resources/spiffe_secret_backend_role#use_jti_claim SpiffeSecretBackendRole#use_jti_claim}
	UseJtiClaim interface{} `field:"optional" json:"useJtiClaim" yaml:"useJtiClaim"`
}

