// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package kubernetessecretbackend

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-vault.kubernetesSecretBackend.KubernetesSecretBackend",
		reflect.TypeOf((*KubernetesSecretBackend)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accessor", GoGetter: "Accessor"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "allowedManagedKeys", GoGetter: "AllowedManagedKeys"},
			_jsii_.MemberProperty{JsiiProperty: "allowedManagedKeysInput", GoGetter: "AllowedManagedKeysInput"},
			_jsii_.MemberProperty{JsiiProperty: "allowedResponseHeaders", GoGetter: "AllowedResponseHeaders"},
			_jsii_.MemberProperty{JsiiProperty: "allowedResponseHeadersInput", GoGetter: "AllowedResponseHeadersInput"},
			_jsii_.MemberProperty{JsiiProperty: "auditNonHmacRequestKeys", GoGetter: "AuditNonHmacRequestKeys"},
			_jsii_.MemberProperty{JsiiProperty: "auditNonHmacRequestKeysInput", GoGetter: "AuditNonHmacRequestKeysInput"},
			_jsii_.MemberProperty{JsiiProperty: "auditNonHmacResponseKeys", GoGetter: "AuditNonHmacResponseKeys"},
			_jsii_.MemberProperty{JsiiProperty: "auditNonHmacResponseKeysInput", GoGetter: "AuditNonHmacResponseKeysInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "defaultLeaseTtlSeconds", GoGetter: "DefaultLeaseTtlSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "defaultLeaseTtlSecondsInput", GoGetter: "DefaultLeaseTtlSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "delegatedAuthAccessors", GoGetter: "DelegatedAuthAccessors"},
			_jsii_.MemberProperty{JsiiProperty: "delegatedAuthAccessorsInput", GoGetter: "DelegatedAuthAccessorsInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "descriptionInput", GoGetter: "DescriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "disableLocalCaJwt", GoGetter: "DisableLocalCaJwt"},
			_jsii_.MemberProperty{JsiiProperty: "disableLocalCaJwtInput", GoGetter: "DisableLocalCaJwtInput"},
			_jsii_.MemberProperty{JsiiProperty: "externalEntropyAccess", GoGetter: "ExternalEntropyAccess"},
			_jsii_.MemberProperty{JsiiProperty: "externalEntropyAccessInput", GoGetter: "ExternalEntropyAccessInput"},
			_jsii_.MemberProperty{JsiiProperty: "forceNoCache", GoGetter: "ForceNoCache"},
			_jsii_.MemberProperty{JsiiProperty: "forceNoCacheInput", GoGetter: "ForceNoCacheInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "identityTokenKey", GoGetter: "IdentityTokenKey"},
			_jsii_.MemberProperty{JsiiProperty: "identityTokenKeyInput", GoGetter: "IdentityTokenKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "kubernetesCaCert", GoGetter: "KubernetesCaCert"},
			_jsii_.MemberProperty{JsiiProperty: "kubernetesCaCertInput", GoGetter: "KubernetesCaCertInput"},
			_jsii_.MemberProperty{JsiiProperty: "kubernetesHost", GoGetter: "KubernetesHost"},
			_jsii_.MemberProperty{JsiiProperty: "kubernetesHostInput", GoGetter: "KubernetesHostInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "listingVisibility", GoGetter: "ListingVisibility"},
			_jsii_.MemberProperty{JsiiProperty: "listingVisibilityInput", GoGetter: "ListingVisibilityInput"},
			_jsii_.MemberProperty{JsiiProperty: "local", GoGetter: "Local"},
			_jsii_.MemberProperty{JsiiProperty: "localInput", GoGetter: "LocalInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxLeaseTtlSeconds", GoGetter: "MaxLeaseTtlSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "maxLeaseTtlSecondsInput", GoGetter: "MaxLeaseTtlSecondsInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "namespace", GoGetter: "Namespace"},
			_jsii_.MemberProperty{JsiiProperty: "namespaceInput", GoGetter: "NamespaceInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "options", GoGetter: "Options"},
			_jsii_.MemberProperty{JsiiProperty: "optionsInput", GoGetter: "OptionsInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "passthroughRequestHeaders", GoGetter: "PassthroughRequestHeaders"},
			_jsii_.MemberProperty{JsiiProperty: "passthroughRequestHeadersInput", GoGetter: "PassthroughRequestHeadersInput"},
			_jsii_.MemberProperty{JsiiProperty: "path", GoGetter: "Path"},
			_jsii_.MemberProperty{JsiiProperty: "pathInput", GoGetter: "PathInput"},
			_jsii_.MemberProperty{JsiiProperty: "pluginVersion", GoGetter: "PluginVersion"},
			_jsii_.MemberProperty{JsiiProperty: "pluginVersionInput", GoGetter: "PluginVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowedManagedKeys", GoMethod: "ResetAllowedManagedKeys"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowedResponseHeaders", GoMethod: "ResetAllowedResponseHeaders"},
			_jsii_.MemberMethod{JsiiMethod: "resetAuditNonHmacRequestKeys", GoMethod: "ResetAuditNonHmacRequestKeys"},
			_jsii_.MemberMethod{JsiiMethod: "resetAuditNonHmacResponseKeys", GoMethod: "ResetAuditNonHmacResponseKeys"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultLeaseTtlSeconds", GoMethod: "ResetDefaultLeaseTtlSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetDelegatedAuthAccessors", GoMethod: "ResetDelegatedAuthAccessors"},
			_jsii_.MemberMethod{JsiiMethod: "resetDescription", GoMethod: "ResetDescription"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableLocalCaJwt", GoMethod: "ResetDisableLocalCaJwt"},
			_jsii_.MemberMethod{JsiiMethod: "resetExternalEntropyAccess", GoMethod: "ResetExternalEntropyAccess"},
			_jsii_.MemberMethod{JsiiMethod: "resetForceNoCache", GoMethod: "ResetForceNoCache"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIdentityTokenKey", GoMethod: "ResetIdentityTokenKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetKubernetesCaCert", GoMethod: "ResetKubernetesCaCert"},
			_jsii_.MemberMethod{JsiiMethod: "resetKubernetesHost", GoMethod: "ResetKubernetesHost"},
			_jsii_.MemberMethod{JsiiMethod: "resetListingVisibility", GoMethod: "ResetListingVisibility"},
			_jsii_.MemberMethod{JsiiMethod: "resetLocal", GoMethod: "ResetLocal"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxLeaseTtlSeconds", GoMethod: "ResetMaxLeaseTtlSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetNamespace", GoMethod: "ResetNamespace"},
			_jsii_.MemberMethod{JsiiMethod: "resetOptions", GoMethod: "ResetOptions"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPassthroughRequestHeaders", GoMethod: "ResetPassthroughRequestHeaders"},
			_jsii_.MemberMethod{JsiiMethod: "resetPluginVersion", GoMethod: "ResetPluginVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetSealWrap", GoMethod: "ResetSealWrap"},
			_jsii_.MemberMethod{JsiiMethod: "resetServiceAccountJwt", GoMethod: "ResetServiceAccountJwt"},
			_jsii_.MemberMethod{JsiiMethod: "resetServiceAccountJwtWo", GoMethod: "ResetServiceAccountJwtWo"},
			_jsii_.MemberMethod{JsiiMethod: "resetServiceAccountJwtWoVersion", GoMethod: "ResetServiceAccountJwtWoVersion"},
			_jsii_.MemberProperty{JsiiProperty: "sealWrap", GoGetter: "SealWrap"},
			_jsii_.MemberProperty{JsiiProperty: "sealWrapInput", GoGetter: "SealWrapInput"},
			_jsii_.MemberProperty{JsiiProperty: "serviceAccountJwt", GoGetter: "ServiceAccountJwt"},
			_jsii_.MemberProperty{JsiiProperty: "serviceAccountJwtInput", GoGetter: "ServiceAccountJwtInput"},
			_jsii_.MemberProperty{JsiiProperty: "serviceAccountJwtWo", GoGetter: "ServiceAccountJwtWo"},
			_jsii_.MemberProperty{JsiiProperty: "serviceAccountJwtWoInput", GoGetter: "ServiceAccountJwtWoInput"},
			_jsii_.MemberProperty{JsiiProperty: "serviceAccountJwtWoVersion", GoGetter: "ServiceAccountJwtWoVersion"},
			_jsii_.MemberProperty{JsiiProperty: "serviceAccountJwtWoVersionInput", GoGetter: "ServiceAccountJwtWoVersionInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "with", GoMethod: "With"},
		},
		func() interface{} {
			j := jsiiProxy_KubernetesSecretBackend{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-vault.kubernetesSecretBackend.KubernetesSecretBackendConfig",
		reflect.TypeOf((*KubernetesSecretBackendConfig)(nil)).Elem(),
	)
}
