// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package ldapauthbackend

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-vault.ldapAuthBackend.LdapAuthBackend",
		reflect.TypeOf((*LdapAuthBackend)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accessor", GoGetter: "Accessor"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "aliasMetadata", GoGetter: "AliasMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "aliasMetadataInput", GoGetter: "AliasMetadataInput"},
			_jsii_.MemberProperty{JsiiProperty: "anonymousGroupSearch", GoGetter: "AnonymousGroupSearch"},
			_jsii_.MemberProperty{JsiiProperty: "anonymousGroupSearchInput", GoGetter: "AnonymousGroupSearchInput"},
			_jsii_.MemberProperty{JsiiProperty: "binddn", GoGetter: "Binddn"},
			_jsii_.MemberProperty{JsiiProperty: "binddnInput", GoGetter: "BinddnInput"},
			_jsii_.MemberProperty{JsiiProperty: "bindpass", GoGetter: "Bindpass"},
			_jsii_.MemberProperty{JsiiProperty: "bindpassInput", GoGetter: "BindpassInput"},
			_jsii_.MemberProperty{JsiiProperty: "bindpassWo", GoGetter: "BindpassWo"},
			_jsii_.MemberProperty{JsiiProperty: "bindpassWoInput", GoGetter: "BindpassWoInput"},
			_jsii_.MemberProperty{JsiiProperty: "bindpassWoVersion", GoGetter: "BindpassWoVersion"},
			_jsii_.MemberProperty{JsiiProperty: "bindpassWoVersionInput", GoGetter: "BindpassWoVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "caseSensitiveNames", GoGetter: "CaseSensitiveNames"},
			_jsii_.MemberProperty{JsiiProperty: "caseSensitiveNamesInput", GoGetter: "CaseSensitiveNamesInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "certificate", GoGetter: "Certificate"},
			_jsii_.MemberProperty{JsiiProperty: "certificateInput", GoGetter: "CertificateInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientTlsCert", GoGetter: "ClientTlsCert"},
			_jsii_.MemberProperty{JsiiProperty: "clientTlsCertInput", GoGetter: "ClientTlsCertInput"},
			_jsii_.MemberProperty{JsiiProperty: "clientTlsKey", GoGetter: "ClientTlsKey"},
			_jsii_.MemberProperty{JsiiProperty: "clientTlsKeyInput", GoGetter: "ClientTlsKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "connectionTimeout", GoGetter: "ConnectionTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "connectionTimeoutInput", GoGetter: "ConnectionTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "denyNullBind", GoGetter: "DenyNullBind"},
			_jsii_.MemberProperty{JsiiProperty: "denyNullBindInput", GoGetter: "DenyNullBindInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "dereferenceAliases", GoGetter: "DereferenceAliases"},
			_jsii_.MemberProperty{JsiiProperty: "dereferenceAliasesInput", GoGetter: "DereferenceAliasesInput"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "descriptionInput", GoGetter: "DescriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "disableAutomatedRotation", GoGetter: "DisableAutomatedRotation"},
			_jsii_.MemberProperty{JsiiProperty: "disableAutomatedRotationInput", GoGetter: "DisableAutomatedRotationInput"},
			_jsii_.MemberProperty{JsiiProperty: "disableRemount", GoGetter: "DisableRemount"},
			_jsii_.MemberProperty{JsiiProperty: "disableRemountInput", GoGetter: "DisableRemountInput"},
			_jsii_.MemberProperty{JsiiProperty: "discoverdn", GoGetter: "Discoverdn"},
			_jsii_.MemberProperty{JsiiProperty: "discoverdnInput", GoGetter: "DiscoverdnInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableSamaccountnameLogin", GoGetter: "EnableSamaccountnameLogin"},
			_jsii_.MemberProperty{JsiiProperty: "enableSamaccountnameLoginInput", GoGetter: "EnableSamaccountnameLoginInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "groupattr", GoGetter: "Groupattr"},
			_jsii_.MemberProperty{JsiiProperty: "groupattrInput", GoGetter: "GroupattrInput"},
			_jsii_.MemberProperty{JsiiProperty: "groupdn", GoGetter: "Groupdn"},
			_jsii_.MemberProperty{JsiiProperty: "groupdnInput", GoGetter: "GroupdnInput"},
			_jsii_.MemberProperty{JsiiProperty: "groupfilter", GoGetter: "Groupfilter"},
			_jsii_.MemberProperty{JsiiProperty: "groupfilterInput", GoGetter: "GroupfilterInput"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberProperty{JsiiProperty: "insecureTls", GoGetter: "InsecureTls"},
			_jsii_.MemberProperty{JsiiProperty: "insecureTlsInput", GoGetter: "InsecureTlsInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "local", GoGetter: "Local"},
			_jsii_.MemberProperty{JsiiProperty: "localInput", GoGetter: "LocalInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxPageSize", GoGetter: "MaxPageSize"},
			_jsii_.MemberProperty{JsiiProperty: "maxPageSizeInput", GoGetter: "MaxPageSizeInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "namespace", GoGetter: "Namespace"},
			_jsii_.MemberProperty{JsiiProperty: "namespaceInput", GoGetter: "NamespaceInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "path", GoGetter: "Path"},
			_jsii_.MemberProperty{JsiiProperty: "pathInput", GoGetter: "PathInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putTune", GoMethod: "PutTune"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "requestTimeout", GoGetter: "RequestTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "requestTimeoutInput", GoGetter: "RequestTimeoutInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAliasMetadata", GoMethod: "ResetAliasMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "resetAnonymousGroupSearch", GoMethod: "ResetAnonymousGroupSearch"},
			_jsii_.MemberMethod{JsiiMethod: "resetBinddn", GoMethod: "ResetBinddn"},
			_jsii_.MemberMethod{JsiiMethod: "resetBindpass", GoMethod: "ResetBindpass"},
			_jsii_.MemberMethod{JsiiMethod: "resetBindpassWo", GoMethod: "ResetBindpassWo"},
			_jsii_.MemberMethod{JsiiMethod: "resetBindpassWoVersion", GoMethod: "ResetBindpassWoVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetCaseSensitiveNames", GoMethod: "ResetCaseSensitiveNames"},
			_jsii_.MemberMethod{JsiiMethod: "resetCertificate", GoMethod: "ResetCertificate"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientTlsCert", GoMethod: "ResetClientTlsCert"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientTlsKey", GoMethod: "ResetClientTlsKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetConnectionTimeout", GoMethod: "ResetConnectionTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetDenyNullBind", GoMethod: "ResetDenyNullBind"},
			_jsii_.MemberMethod{JsiiMethod: "resetDereferenceAliases", GoMethod: "ResetDereferenceAliases"},
			_jsii_.MemberMethod{JsiiMethod: "resetDescription", GoMethod: "ResetDescription"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableAutomatedRotation", GoMethod: "ResetDisableAutomatedRotation"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisableRemount", GoMethod: "ResetDisableRemount"},
			_jsii_.MemberMethod{JsiiMethod: "resetDiscoverdn", GoMethod: "ResetDiscoverdn"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableSamaccountnameLogin", GoMethod: "ResetEnableSamaccountnameLogin"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupattr", GoMethod: "ResetGroupattr"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupdn", GoMethod: "ResetGroupdn"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupfilter", GoMethod: "ResetGroupfilter"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetInsecureTls", GoMethod: "ResetInsecureTls"},
			_jsii_.MemberMethod{JsiiMethod: "resetLocal", GoMethod: "ResetLocal"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxPageSize", GoMethod: "ResetMaxPageSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetNamespace", GoMethod: "ResetNamespace"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPath", GoMethod: "ResetPath"},
			_jsii_.MemberMethod{JsiiMethod: "resetRequestTimeout", GoMethod: "ResetRequestTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetRotationPeriod", GoMethod: "ResetRotationPeriod"},
			_jsii_.MemberMethod{JsiiMethod: "resetRotationSchedule", GoMethod: "ResetRotationSchedule"},
			_jsii_.MemberMethod{JsiiMethod: "resetRotationWindow", GoMethod: "ResetRotationWindow"},
			_jsii_.MemberMethod{JsiiMethod: "resetStarttls", GoMethod: "ResetStarttls"},
			_jsii_.MemberMethod{JsiiMethod: "resetTlsMaxVersion", GoMethod: "ResetTlsMaxVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetTlsMinVersion", GoMethod: "ResetTlsMinVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenBoundCidrs", GoMethod: "ResetTokenBoundCidrs"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenExplicitMaxTtl", GoMethod: "ResetTokenExplicitMaxTtl"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenMaxTtl", GoMethod: "ResetTokenMaxTtl"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenNoDefaultPolicy", GoMethod: "ResetTokenNoDefaultPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenNumUses", GoMethod: "ResetTokenNumUses"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenPeriod", GoMethod: "ResetTokenPeriod"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenPolicies", GoMethod: "ResetTokenPolicies"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenTtl", GoMethod: "ResetTokenTtl"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenType", GoMethod: "ResetTokenType"},
			_jsii_.MemberMethod{JsiiMethod: "resetTune", GoMethod: "ResetTune"},
			_jsii_.MemberMethod{JsiiMethod: "resetUpndomain", GoMethod: "ResetUpndomain"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserattr", GoMethod: "ResetUserattr"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserdn", GoMethod: "ResetUserdn"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserfilter", GoMethod: "ResetUserfilter"},
			_jsii_.MemberMethod{JsiiMethod: "resetUsernameAsAlias", GoMethod: "ResetUsernameAsAlias"},
			_jsii_.MemberMethod{JsiiMethod: "resetUseTokenGroups", GoMethod: "ResetUseTokenGroups"},
			_jsii_.MemberProperty{JsiiProperty: "rotationPeriod", GoGetter: "RotationPeriod"},
			_jsii_.MemberProperty{JsiiProperty: "rotationPeriodInput", GoGetter: "RotationPeriodInput"},
			_jsii_.MemberProperty{JsiiProperty: "rotationSchedule", GoGetter: "RotationSchedule"},
			_jsii_.MemberProperty{JsiiProperty: "rotationScheduleInput", GoGetter: "RotationScheduleInput"},
			_jsii_.MemberProperty{JsiiProperty: "rotationWindow", GoGetter: "RotationWindow"},
			_jsii_.MemberProperty{JsiiProperty: "rotationWindowInput", GoGetter: "RotationWindowInput"},
			_jsii_.MemberProperty{JsiiProperty: "starttls", GoGetter: "Starttls"},
			_jsii_.MemberProperty{JsiiProperty: "starttlsInput", GoGetter: "StarttlsInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "tlsMaxVersion", GoGetter: "TlsMaxVersion"},
			_jsii_.MemberProperty{JsiiProperty: "tlsMaxVersionInput", GoGetter: "TlsMaxVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "tlsMinVersion", GoGetter: "TlsMinVersion"},
			_jsii_.MemberProperty{JsiiProperty: "tlsMinVersionInput", GoGetter: "TlsMinVersionInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "tokenBoundCidrs", GoGetter: "TokenBoundCidrs"},
			_jsii_.MemberProperty{JsiiProperty: "tokenBoundCidrsInput", GoGetter: "TokenBoundCidrsInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenExplicitMaxTtl", GoGetter: "TokenExplicitMaxTtl"},
			_jsii_.MemberProperty{JsiiProperty: "tokenExplicitMaxTtlInput", GoGetter: "TokenExplicitMaxTtlInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenMaxTtl", GoGetter: "TokenMaxTtl"},
			_jsii_.MemberProperty{JsiiProperty: "tokenMaxTtlInput", GoGetter: "TokenMaxTtlInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenNoDefaultPolicy", GoGetter: "TokenNoDefaultPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "tokenNoDefaultPolicyInput", GoGetter: "TokenNoDefaultPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenNumUses", GoGetter: "TokenNumUses"},
			_jsii_.MemberProperty{JsiiProperty: "tokenNumUsesInput", GoGetter: "TokenNumUsesInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenPeriod", GoGetter: "TokenPeriod"},
			_jsii_.MemberProperty{JsiiProperty: "tokenPeriodInput", GoGetter: "TokenPeriodInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenPolicies", GoGetter: "TokenPolicies"},
			_jsii_.MemberProperty{JsiiProperty: "tokenPoliciesInput", GoGetter: "TokenPoliciesInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenTtl", GoGetter: "TokenTtl"},
			_jsii_.MemberProperty{JsiiProperty: "tokenTtlInput", GoGetter: "TokenTtlInput"},
			_jsii_.MemberProperty{JsiiProperty: "tokenType", GoGetter: "TokenType"},
			_jsii_.MemberProperty{JsiiProperty: "tokenTypeInput", GoGetter: "TokenTypeInput"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "tune", GoGetter: "Tune"},
			_jsii_.MemberProperty{JsiiProperty: "tuneInput", GoGetter: "TuneInput"},
			_jsii_.MemberProperty{JsiiProperty: "upndomain", GoGetter: "Upndomain"},
			_jsii_.MemberProperty{JsiiProperty: "upndomainInput", GoGetter: "UpndomainInput"},
			_jsii_.MemberProperty{JsiiProperty: "url", GoGetter: "Url"},
			_jsii_.MemberProperty{JsiiProperty: "urlInput", GoGetter: "UrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "userattr", GoGetter: "Userattr"},
			_jsii_.MemberProperty{JsiiProperty: "userattrInput", GoGetter: "UserattrInput"},
			_jsii_.MemberProperty{JsiiProperty: "userdn", GoGetter: "Userdn"},
			_jsii_.MemberProperty{JsiiProperty: "userdnInput", GoGetter: "UserdnInput"},
			_jsii_.MemberProperty{JsiiProperty: "userfilter", GoGetter: "Userfilter"},
			_jsii_.MemberProperty{JsiiProperty: "userfilterInput", GoGetter: "UserfilterInput"},
			_jsii_.MemberProperty{JsiiProperty: "usernameAsAlias", GoGetter: "UsernameAsAlias"},
			_jsii_.MemberProperty{JsiiProperty: "usernameAsAliasInput", GoGetter: "UsernameAsAliasInput"},
			_jsii_.MemberProperty{JsiiProperty: "useTokenGroups", GoGetter: "UseTokenGroups"},
			_jsii_.MemberProperty{JsiiProperty: "useTokenGroupsInput", GoGetter: "UseTokenGroupsInput"},
		},
		func() interface{} {
			j := jsiiProxy_LdapAuthBackend{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-vault.ldapAuthBackend.LdapAuthBackendConfig",
		reflect.TypeOf((*LdapAuthBackendConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-vault.ldapAuthBackend.LdapAuthBackendTune",
		reflect.TypeOf((*LdapAuthBackendTune)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktn/provider-vault.ldapAuthBackend.LdapAuthBackendTuneList",
		reflect.TypeOf((*LdapAuthBackendTuneList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_LdapAuthBackendTuneList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktn/provider-vault.ldapAuthBackend.LdapAuthBackendTuneOutputReference",
		reflect.TypeOf((*LdapAuthBackendTuneOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "allowedResponseHeaders", GoGetter: "AllowedResponseHeaders"},
			_jsii_.MemberProperty{JsiiProperty: "allowedResponseHeadersInput", GoGetter: "AllowedResponseHeadersInput"},
			_jsii_.MemberProperty{JsiiProperty: "auditNonHmacRequestKeys", GoGetter: "AuditNonHmacRequestKeys"},
			_jsii_.MemberProperty{JsiiProperty: "auditNonHmacRequestKeysInput", GoGetter: "AuditNonHmacRequestKeysInput"},
			_jsii_.MemberProperty{JsiiProperty: "auditNonHmacResponseKeys", GoGetter: "AuditNonHmacResponseKeys"},
			_jsii_.MemberProperty{JsiiProperty: "auditNonHmacResponseKeysInput", GoGetter: "AuditNonHmacResponseKeysInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "defaultLeaseTtl", GoGetter: "DefaultLeaseTtl"},
			_jsii_.MemberProperty{JsiiProperty: "defaultLeaseTtlInput", GoGetter: "DefaultLeaseTtlInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "listingVisibility", GoGetter: "ListingVisibility"},
			_jsii_.MemberProperty{JsiiProperty: "listingVisibilityInput", GoGetter: "ListingVisibilityInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxLeaseTtl", GoGetter: "MaxLeaseTtl"},
			_jsii_.MemberProperty{JsiiProperty: "maxLeaseTtlInput", GoGetter: "MaxLeaseTtlInput"},
			_jsii_.MemberProperty{JsiiProperty: "passthroughRequestHeaders", GoGetter: "PassthroughRequestHeaders"},
			_jsii_.MemberProperty{JsiiProperty: "passthroughRequestHeadersInput", GoGetter: "PassthroughRequestHeadersInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowedResponseHeaders", GoMethod: "ResetAllowedResponseHeaders"},
			_jsii_.MemberMethod{JsiiMethod: "resetAuditNonHmacRequestKeys", GoMethod: "ResetAuditNonHmacRequestKeys"},
			_jsii_.MemberMethod{JsiiMethod: "resetAuditNonHmacResponseKeys", GoMethod: "ResetAuditNonHmacResponseKeys"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultLeaseTtl", GoMethod: "ResetDefaultLeaseTtl"},
			_jsii_.MemberMethod{JsiiMethod: "resetListingVisibility", GoMethod: "ResetListingVisibility"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxLeaseTtl", GoMethod: "ResetMaxLeaseTtl"},
			_jsii_.MemberMethod{JsiiMethod: "resetPassthroughRequestHeaders", GoMethod: "ResetPassthroughRequestHeaders"},
			_jsii_.MemberMethod{JsiiMethod: "resetTokenType", GoMethod: "ResetTokenType"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "tokenType", GoGetter: "TokenType"},
			_jsii_.MemberProperty{JsiiProperty: "tokenTypeInput", GoGetter: "TokenTypeInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_LdapAuthBackendTuneOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnComplexObject)
			return &j
		},
	)
}
