// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package pkisecretbackendcert

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-vault.pkiSecretBackendCert.PkiSecretBackendCert",
		reflect.TypeOf((*PkiSecretBackendCert)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "altNames", GoGetter: "AltNames"},
			_jsii_.MemberProperty{JsiiProperty: "altNamesInput", GoGetter: "AltNamesInput"},
			_jsii_.MemberProperty{JsiiProperty: "autoRenew", GoGetter: "AutoRenew"},
			_jsii_.MemberProperty{JsiiProperty: "autoRenewInput", GoGetter: "AutoRenewInput"},
			_jsii_.MemberProperty{JsiiProperty: "backend", GoGetter: "Backend"},
			_jsii_.MemberProperty{JsiiProperty: "backendInput", GoGetter: "BackendInput"},
			_jsii_.MemberProperty{JsiiProperty: "caChain", GoGetter: "CaChain"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "certificate", GoGetter: "Certificate"},
			_jsii_.MemberProperty{JsiiProperty: "certMetadata", GoGetter: "CertMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "certMetadataInput", GoGetter: "CertMetadataInput"},
			_jsii_.MemberProperty{JsiiProperty: "commonName", GoGetter: "CommonName"},
			_jsii_.MemberProperty{JsiiProperty: "commonNameInput", GoGetter: "CommonNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "excludeCnFromSans", GoGetter: "ExcludeCnFromSans"},
			_jsii_.MemberProperty{JsiiProperty: "excludeCnFromSansInput", GoGetter: "ExcludeCnFromSansInput"},
			_jsii_.MemberProperty{JsiiProperty: "expiration", GoGetter: "Expiration"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "format", GoGetter: "Format"},
			_jsii_.MemberProperty{JsiiProperty: "formatInput", GoGetter: "FormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ipSans", GoGetter: "IpSans"},
			_jsii_.MemberProperty{JsiiProperty: "ipSansInput", GoGetter: "IpSansInput"},
			_jsii_.MemberProperty{JsiiProperty: "issuerRef", GoGetter: "IssuerRef"},
			_jsii_.MemberProperty{JsiiProperty: "issuerRefInput", GoGetter: "IssuerRefInput"},
			_jsii_.MemberProperty{JsiiProperty: "issuingCa", GoGetter: "IssuingCa"},
			_jsii_.MemberProperty{JsiiProperty: "jksPassword", GoGetter: "JksPassword"},
			_jsii_.MemberProperty{JsiiProperty: "jksPasswordInput", GoGetter: "JksPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "jksPrivateKeyAlias", GoGetter: "JksPrivateKeyAlias"},
			_jsii_.MemberProperty{JsiiProperty: "jksPrivateKeyAliasInput", GoGetter: "JksPrivateKeyAliasInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "minSecondsRemaining", GoGetter: "MinSecondsRemaining"},
			_jsii_.MemberProperty{JsiiProperty: "minSecondsRemainingInput", GoGetter: "MinSecondsRemainingInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "namespace", GoGetter: "Namespace"},
			_jsii_.MemberProperty{JsiiProperty: "namespaceInput", GoGetter: "NamespaceInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "notAfter", GoGetter: "NotAfter"},
			_jsii_.MemberProperty{JsiiProperty: "notAfterInput", GoGetter: "NotAfterInput"},
			_jsii_.MemberProperty{JsiiProperty: "otherSans", GoGetter: "OtherSans"},
			_jsii_.MemberProperty{JsiiProperty: "otherSansInput", GoGetter: "OtherSansInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "pkcs12Encoder", GoGetter: "Pkcs12Encoder"},
			_jsii_.MemberProperty{JsiiProperty: "pkcs12EncoderInput", GoGetter: "Pkcs12EncoderInput"},
			_jsii_.MemberProperty{JsiiProperty: "pkcs12Password", GoGetter: "Pkcs12Password"},
			_jsii_.MemberProperty{JsiiProperty: "pkcs12PasswordInput", GoGetter: "Pkcs12PasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "privateKey", GoGetter: "PrivateKey"},
			_jsii_.MemberProperty{JsiiProperty: "privateKeyFormat", GoGetter: "PrivateKeyFormat"},
			_jsii_.MemberProperty{JsiiProperty: "privateKeyFormatInput", GoGetter: "PrivateKeyFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "privateKeyType", GoGetter: "PrivateKeyType"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "removeRootsFromChain", GoGetter: "RemoveRootsFromChain"},
			_jsii_.MemberProperty{JsiiProperty: "removeRootsFromChainInput", GoGetter: "RemoveRootsFromChainInput"},
			_jsii_.MemberProperty{JsiiProperty: "renewPending", GoGetter: "RenewPending"},
			_jsii_.MemberMethod{JsiiMethod: "resetAltNames", GoMethod: "ResetAltNames"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutoRenew", GoMethod: "ResetAutoRenew"},
			_jsii_.MemberMethod{JsiiMethod: "resetCertMetadata", GoMethod: "ResetCertMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "resetExcludeCnFromSans", GoMethod: "ResetExcludeCnFromSans"},
			_jsii_.MemberMethod{JsiiMethod: "resetFormat", GoMethod: "ResetFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpSans", GoMethod: "ResetIpSans"},
			_jsii_.MemberMethod{JsiiMethod: "resetIssuerRef", GoMethod: "ResetIssuerRef"},
			_jsii_.MemberMethod{JsiiMethod: "resetJksPassword", GoMethod: "ResetJksPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetJksPrivateKeyAlias", GoMethod: "ResetJksPrivateKeyAlias"},
			_jsii_.MemberMethod{JsiiMethod: "resetMinSecondsRemaining", GoMethod: "ResetMinSecondsRemaining"},
			_jsii_.MemberMethod{JsiiMethod: "resetNamespace", GoMethod: "ResetNamespace"},
			_jsii_.MemberMethod{JsiiMethod: "resetNotAfter", GoMethod: "ResetNotAfter"},
			_jsii_.MemberMethod{JsiiMethod: "resetOtherSans", GoMethod: "ResetOtherSans"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPkcs12Encoder", GoMethod: "ResetPkcs12Encoder"},
			_jsii_.MemberMethod{JsiiMethod: "resetPkcs12Password", GoMethod: "ResetPkcs12Password"},
			_jsii_.MemberMethod{JsiiMethod: "resetPrivateKeyFormat", GoMethod: "ResetPrivateKeyFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetRemoveRootsFromChain", GoMethod: "ResetRemoveRootsFromChain"},
			_jsii_.MemberMethod{JsiiMethod: "resetRevoke", GoMethod: "ResetRevoke"},
			_jsii_.MemberMethod{JsiiMethod: "resetRevokeWithKey", GoMethod: "ResetRevokeWithKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetTtl", GoMethod: "ResetTtl"},
			_jsii_.MemberMethod{JsiiMethod: "resetUriSans", GoMethod: "ResetUriSans"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserIds", GoMethod: "ResetUserIds"},
			_jsii_.MemberProperty{JsiiProperty: "revoke", GoGetter: "Revoke"},
			_jsii_.MemberProperty{JsiiProperty: "revokeInput", GoGetter: "RevokeInput"},
			_jsii_.MemberProperty{JsiiProperty: "revokeWithKey", GoGetter: "RevokeWithKey"},
			_jsii_.MemberProperty{JsiiProperty: "revokeWithKeyInput", GoGetter: "RevokeWithKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "serialNumber", GoGetter: "SerialNumber"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "ttl", GoGetter: "Ttl"},
			_jsii_.MemberProperty{JsiiProperty: "ttlInput", GoGetter: "TtlInput"},
			_jsii_.MemberProperty{JsiiProperty: "uriSans", GoGetter: "UriSans"},
			_jsii_.MemberProperty{JsiiProperty: "uriSansInput", GoGetter: "UriSansInput"},
			_jsii_.MemberProperty{JsiiProperty: "userIds", GoGetter: "UserIds"},
			_jsii_.MemberProperty{JsiiProperty: "userIdsInput", GoGetter: "UserIdsInput"},
			_jsii_.MemberMethod{JsiiMethod: "with", GoMethod: "With"},
		},
		func() interface{} {
			j := jsiiProxy_PkiSecretBackendCert{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-vault.pkiSecretBackendCert.PkiSecretBackendCertConfig",
		reflect.TypeOf((*PkiSecretBackendCertConfig)(nil)).Elem(),
	)
}
